### PR TITLE
fix build error

### PR DESCRIPTION
**Pull request by bangdc90**
I also want to eliminate building for LVGL's examples, but it is subproject link, so I don't know how to do

### CODE REVIEW

**Comment by MarioFPVdev** [comment]
Please try to contribute with additional source code to include OSD based on the lvgl library. 
Removing these lines is a step backwards, not forward.

**Review by MarioFPVdev — CHANGES_REQUESTED** [review]
This pull request will remove the lvgl library from vdec.

**Comment by bangdc90** [comment]
> This pull request will remove the lvgl library from vdec.

lvgl library is still built man, i just mean that remove unnecessary targets, so you will dont see them when building.
Anw, just be my opinion, It saves time for development :)

**Comment by MarioFPVdev** [comment]
Please contribute source code that will use the lvgl library. Thank you.

**Comment by bangdc90** [comment]
> Please contribute source code that will use the lvgl library. Thank you.

For sure :)

**Comment by iHardRock** [comment]
This pull request will not be accepted

**Pull request closed without merging**
